[package]
name = "diffsol-testing"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.5.1"

pharmsol_053 = { version = "=0.7.9-rc1", package = "pharmsol" }
pharmsol_030 = { version = "=0.7.9-rc2", package = "pharmsol" }


[[bench]]
name = "pmcore"
harness = false
